### ISSUE TITLE
not appear in module 

### ISSUE THREAD

**Issue by xbahaa** [yezyilomo/odoo-rest-api#13]
after doing this 

Download this module and put it to your Odoo addons directory
Install requirements with pip install -r requirements.txt

the module not appear in apps 

so what to do i download a zip file form the git then put it in the addons file and try to search for it in apps but i cant find it so i tried it call it the only api that worked this one 

POST /web/session/authenticate/

**Comment by yezyilomo** [comment]
You could delete Apps filter and find it, but no need anymore cuz I've fixed it already.
