### ISSUE TITLE
Cross Origin Issue

### ISSUE THREAD

**Issue by briceamk** [yezyilomo/odoo-rest-api#16]
Hello,
First I want to thnks your for this great work.
When I send request to odoo with Postman, it work very well,  but when i use angular i get this error

Access to XMLHttpRequest at 'http://192.168.10.133:8005/api/hr.employee?session_id=f86f5ac6d2f53213c1c4d963fdf6c21233685876' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

can't you help me please?

**Comment by naibor** [comment]
Hello,
You will have to consume the exposed endpoints with your own  API

**Comment by yezyilomo** [comment]
Am closing this as your case looks like it has something to do with Angular rather than this module.
