### ISSUE TITLE
About Call an Odoo action from API REST

### ISSUE THREAD

**Issue by joseluisbossio** [yezyilomo/odoo-rest-api#23]
Hi, do you know if I could call an ODOO action from odoo-rest-api?

For example: 

https://<hostname>/web?#menu_id=181&action=277

Thanks!
JL

**Comment by yezyilomo** [comment]
You can only call model methods, so if your action is associated with the model you can do that other than that no.

**Comment by yezyilomo** [comment]
Am closing this as there is no plan to support this for now.
