### ISSUE TITLE
AttributeError: 'res.users' object has no attribute 'fields_get_keys'

### ISSUE THREAD

**Issue by NaveenReddy198** [yezyilomo/odoo-rest-api#78]
Hii team iam trying to use odoo Rest Apis and when i try to fetch list of users with Api :  /api/res.users/  iam getting error : AttributeError: 'res.users' object has no attribute 'fields_get_keys' . Can u guys help me.

**Comment by yezyilomo** [comment]
I believe this #77 has fixed this issue.
